akka {
  loglevel = "INFO"
  
  actor {
    provider = "local"
    
    serialization-bindings {
      "com.uic.cs553.distributed.framework.DistributedMessage" = jackson-json
    }
  }
  
  # Disable warning messages
  coordinated-shutdown {
    exit-jvm = on
  }
}

sim {
  seed = 1
  runForSeconds = 5

  graph {
    ringN = 8
  }

  traffic {
    tickEveryMs = 100
  }
}
