sim {
  seed = 1
  runForSeconds = 8

  graph { ringN = 8 }

  edgeLabeling {
    default = [ "CONTROL", "PING" ]
  }

  traffic {
    default { family = "uniform", kinds = [ "PING" ] }
  }

  initiators {
    timers = [
      { node = 0, tickEveryMs = 100, mode = "pdf" }
    ]
    inputs = [ { node = 0 } ]
  }
}

